### ISSUE TITLE
Travis CI fails with pull requests

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#255]
```
0.45s$ jspm config registries.github.auth JSPM_GITHUB_AUTH_TOKEN
0.53s$ node_modules/.bin/jspm install
err  URIError: URI malformed
         at decodeURIComponent (native)
         at decodeCredentials (/home/travis/build/aurelia-ui-toolkits/aurelia-kendoui-plugin/node_modules/jspm-github/github.js:56:15)
         at Object.GithubLocation (/home/travis/build/aurelia-ui-toolkits/aurelia-kendoui-plugin/node_modules/jspm-github/github.js:100:17)
         at Object.exports.load (/home/travis/build/aurelia-ui-toolkits/aurelia-kendoui-plugin/node_modules/jspm/lib/registry.js:73:56)
         at new RegistryPath (/home/travis/build/aurelia-ui-toolkits/aurelia-kendoui-plugin/node_modules/jspm/lib/config/loader.js:264:33)
         at Config.read (/home/travis/build/aurelia-ui-toolkits/aurelia-kendoui-plugin/node_modules/jspm/lib/config/loader.js:127:26)
         at /home/travis/build/aurelia-ui-toolkits/aurelia-kendoui-plugin/node_modules/jspm/lib/config.js:100:26
         at process._tickCallback (node.js:401:9)
         at Function.Module.runMain (module.js:431:11)
         at startup (node.js:139:18)
         at node.js:999:3
err  Unable to load registry github
warn Installation changes not saved.
The command "node_modules/.bin/jspm install" failed and exited with 1 during .
```

**Comment by JeroenVinke** [comment]
[this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/39ee4a0e2382456a36ad132895c5e00d4885b65e) may have fixed it

**Comment by charlespockert** [comment]
@JeroenVinke just PRd with no issues here - shall we close this for now?

**Comment by JeroenVinke** [comment]
yeah sure
