### ISSUE TITLE
Bundling error

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#274]
If you get this error during bundling:

```
[17:50:31] Error tracing npm:aurelia-kendoui-bridge@0.1.0/autocomplete/autocomplete at file:///D:/Downloads/skeleton-navigation-master/skeleton-navigation-master/skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wwwroot/jspm_packages/npm/aurelia-kendoui-bridge@0.1.0/autocomplete/autocomplete.js
        Error: Unable to calculate canonical name to bundle file:///vendors/js/kendo.autocomplete.min.js. Ensure that this module sits within the baseURL or a wildcard path config.
    at getCanonicalNamePlain (D:\Downloads\skeleton-navigation-master\skeleton-navigation-master\skeleton-es2016-asp.net5\src\skeleton-navigation-es2016-vs\node_modules\systemjs-builder\lib\utils.js:205:13)
    at getCanonicalName (D:\Downloads\skeleton-navigation-master\skeleton-navigation-master\skeleton-es2016-asp.net5\src\skeleton-navigation-es2016-vs\node_modules\systemjs-builder\lib\utils.js:130:19)
    at D:\Downloads\skeleton-navigation-master\skeleton-navigation-master\skeleton-es2016-asp.net5\src\skeleton-navigation-es2016-vs\node_modules\systemjs-builder\lib\trace.js:426:36
    at run (D:\Downloads\skeleton-navigation-master\skeleton-navigation-master\skeleton-es2016-asp.net5\src\skeleton-navigation-es2016-vs\node_modules\karma\node_modules\core-js\modules\es6.promise.js:112:47)
    at D:\Downloads\skeleton-navigation-master\skeleton-navigation-master\skeleton-es2016-asp.net5\src\skeleton-navigation-es2016-vs\node_modules\karma\node_modules\core-js\modules\es6.promise.js:123:28
    at flush (D:\Downloads\skeleton-navigation-master\skeleton-navigation-master\skeleton-es2016-asp.net5\src\skeleton-navigation-es2016-vs\node_modules\karma\node_modules\core-js\modules\_microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
```

Instead of having a mapping of `"kendo-ui": "/vendors"` in the map section, add a path mapping in the paths section: `"kendo-ui/*": "vendors/*"`,

so it looks like this:
```
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "kendo-ui/*": "vendors/*",
    "kendo.*": "vendors/js/kendo.*.js"
  },
```

**Comment by JeroenVinke** [comment]
idea: instead of the `vendors` folder next to the `src` folder, put a `kendo-ui` folder inside the `src` folder. that way, no mapping is needed

**Comment by JeroenVinke** [comment]
Lets change the installation instructions
