### ISSUE TITLE
control-properties.js error: Cannot read property "widget" of undefined

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia-ui-toolkits/aurelia-kendoui-bridge#348]
Using Kendo version 2016.1.118 from the vendor directory in the `aurelia-kendoui-bridge` repository, attempting to load the plugin with pro features as follows generates an error. 
```
export function configure(aurelia) {
	aurelia.use
		.standardConfiguration()
		.developmentLogging();
    ...
	aurelia.use.plugin('aurelia-kendoui-bridge', (kendo) => kendo.pro());

	aurelia.start().then(a => a.setRoot());
}
```

The errors are as follows:
```
Unhandled promise rejection Error: Cannot read property 'widget' of undefined
	Error loading http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js
    at ControlProperties.getProperties (http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/common/control-properties.js:21:56)
    at http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/common/decorators.js:12:42
    at http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js:86:60
    at Object.<anonymous> (http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js:89:5)
    at i (http://localhost:25779/jspm_packages/system.js:5:11518)
    at i (http://localhost:25779/jspm_packages/system.js:4:31576)
    at n (http://localhost:25779/jspm_packages/system.js:4:30141)
    at Object.execute (http://localhost:25779/jspm_packages/system.js:5:3176)
    at y (http://localhost:25779/jspm_packages/system.js:4:9948)
    at w (http://localhost:25779/jspm_packages/system.js:4:10327)(anonymous function) @ :25779/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:138
:25779/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:138 Unhandled promise rejection Error: Cannot read property 'widget' of undefined
	Error loading http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js
    at ControlProperties.getProperties (http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/common/control-properties.js:21:56)
    at http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/common/decorators.js:12:42
    at http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js:86:60
    at Object.<anonymous> (http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js:89:5)
    at i (http://localhost:25779/jspm_packages/system.js:5:11518)
    at i (http://localhost:25779/jspm_packages/system.js:4:31576)
    at n (http://localhost:25779/jspm_packages/system.js:4:30141)
    at Object.execute (http://localhost:25779/jspm_packages/system.js:5:3176)
    at y (http://localhost:25779/jspm_packages/system.js:4:9948)
    at w (http://localhost:25779/jspm_packages/system.js:4:10327)(anonymous function) @ :25779/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:138
:25779/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:138 Unhandled promise rejection Error: Cannot read property 'widget' of undefined
	Error loading http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js
    at ControlProperties.getProperties (http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/common/control-properties.js:21:56)
    at http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/common/decorators.js:12:42
    at http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js:86:60
    at Object.<anonymous> (http://localhost:25779/jspm_packages/npm/aurelia-kendoui-bridge@0.2.3/grid/grid.js:89:5)
    at i (http://localhost:25779/jspm_packages/system.js:5:11518)
    at i (http://localhost:25779/jspm_packages/system.js:4:31576)
    at n (http://localhost:25779/jspm_packages/system.js:4:30141)
    at Object.execute (http://localhost:25779/jspm_packages/system.js:5:3176)
    at y (http://localhost:25779/jspm_packages/system.js:4:9948)
    at w (http://localhost:25779/jspm_packages/system.js:4:10327)(anonymous function) @ :25779/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:138
```

It seems that the Kendo files being loaded are not adding keys to `$.fn`.

This error also happens if I try calling `kendo.core().kendoGrid()`, but does not happen if I only use the kendo core libraries loaded by using `kendo.core()`. Of note, this only seems to happen for specific widgets - configuring the plugin with `kendo.core().kendoAutoComplete()` works, as does `kendo.core().kendoTreeList()`.

Although my config.js does not match the sample in the installation guide, I have verified that the Kendo libraries are being loaded correctly by SystemJS. I've included the relevant portions of my config.js:

```
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties",
      "runtime"
    ]
  },
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "kendo.*": "dist/vendor/kendo/js/kendo.*.js"
  },

  //meta: {
  //  "dist/vendor/kendo/kendo.*.js": {
  //    "deps": [
  //      "github:components/jquery@2.1.4"
  //    ]
  //  }
  //},

  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.0.2",
    "aurelia-async": "npm:aurelia-async@0.6.1",
    "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
    "aurelia-dialog": "github:jedd-ahyoung/dialog@temp-release",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.0.2",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.7",
    "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.0.1",
    "aurelia-http-client": "npm:aurelia-http-client@1.0.0-beta.1",
    "aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge@0.2.3",
    "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.1",
    "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.1.3",
    "aurelia-logging-network": "github:jedd-ahyoung/logging-network@0.0.2",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
    "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
    "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
    "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
    "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.0.2",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.3",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.4",
    "babel": "npm:babel-core@5.8.25",
    "babel-runtime": "npm:babel-runtime@5.8.25",
    "bootstrap": "github:twbs/bootstrap@3.3.5",
    "clean-css": "npm:clean-css@3.4.9",
    "core-js": "npm:core-js@1.2.1",
    "fetch": "github:github/fetch@0.9.0",
    "font-awesome": "npm:font-awesome@4.4.0",
    "jquery": "github:components/jquery@2.1.4",
    "jquery.min": "github:components/jquery@2.1.4",
    "json": "github:systemjs/plugin-json@0.1.0",
    "kendo-ui": "/vendor/kendo",
```

**Comment by adriatic** [comment]
Check the "spot" pointed by the arrow -t does not seem right

![image](https://cloud.githubusercontent.com/assets/2712405/13092681/57bbc820-d4cf-11e5-83d7-0ef24f451ac9.png)

Also, I please look at **["our" version of the config.js](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/config.js)** file which is being used couple hundred times a day, so statistically is to be considered correct

```
...
paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "kendo-ui/*": "vendors/*",
    "kendo.*": "vendors/js/kendo.*.js"
  },
...
```

**Comment by jedd-ahyoung** [comment]
There was a formatting error in my response (missing a backtick for the code block). I've fixed that.

Note that while my configuration seems different than yours on the surface, it is fundamentally doing the same thing. Further, my directory configuration is different than the sample, as mandated by the needs of our application structure. I have ensured that the Kendo libraries are being loaded correctly by SystemJS.

**Comment by adriatic** [comment]
> Note that while my configuration seems different than yours on the surface

I **think** that I understand the "basic equivalence" - as I do not believe that anyone is really keeping track of jspm "evolution" completely. 

As you mentioned before 

>This error also happens if I try calling kendo.core().kendoGrid()

which (in my opinion is a semantic error), I wanted to be extra careful in looking at your issue with a different set of eyes. So, if I was you, I would start with the working example from **[this collection](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/master/sample/src/samples)** and massage it  very carefully to the shape you need for your project, verifying after each modification that everything still works OK.

I do not believe that your issue can be solved from the **[information you supplied above](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/348#issue-134106628). It seems similar to a patient sending a vial of his blood to the lab, expecting them to find he has a severed hand :-)

**Comment by JeroenVinke** [comment]
@jedd-ahyoung if you can reproduce this with skeleton-navigation we can look into it more, we need to know everything about your setup.

**Comment by jedd-ahyoung** [comment]
@JeroenVinke Yup. I'm doing that right now, actually. I'll try to distill
the issue and see if I can reproduce.

2016-02-17 2:30 GMT-05:00 Jeroen Vinke <notifications@github.com>:

**Comment by JeroenVinke** [comment]
Forks possibly caused this issue (combined with an outdated Kendo version?)
