### ISSUE TITLE
routing problem in the Catalog app

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#398]
I am not sure whether by adding **[this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/daeb949abd0d4a8c002dc5bdb360c399f2867c3f)** change I managed to mess something up or is this problem introduced elsewhere. It **does not exist** in `0.4.0` version

How to reproduce this problem:
**1** Start the app (locally as it does not exist anywhere else yet). Observe that it is the About page that is the default landing page
**2** Click on the `Components Catalog` (left-most) main menu item: the Chrome console shows:

```
ERROR [app-router] TypeError: Cannot read property 'children' of null
    at ue.ui.DataBoundWidget.extend._items (http://localhost:3000/src/root/vendors/js/kendo.grid.min.js:25:31750)
    at ue.ui.DataBoundWidget.extend.items (http://localhost:3000/src/root/vendors/js/kendo.grid.min.js:25:31703)
    at http://localhost:3000/src/root/vendors/js/kendo.core.min.js:26:1190
    at TemplateCompiler.handleTemplateEvents (http://localhost:3000/src/aurelia-kendoui-bridge/common/template-compiler.js:46:22)
    at kendo.ui.Widget.angular (http://localhost:3000/src/aurelia-kendoui-bridge/common/template-compiler.js:29:19)
    at X.extend._angularItems (http://localhost:3000/src/root/vendors/js/kendo.core.min.js:26:1151)
    at ue.ui.DataBoundWidget.extend._angularItems (http://localhost:3000/src/root/vendors/js/kendo.grid.min.js:28:16540)
    at ue.ui.DataBoundWidget.extend.destroy (http://localhost:3000/src/root/vendors/js/kendo.grid.min.js:25:28487)
    at WidgetBase.destroy (http://localhost:3000/src/aurelia-kendoui-bridge/common/widget-base.js:179:18)
    at Grid.detached (http://localhost:3000/src/aurelia-kendoui-bridge/grid/grid.js:111:27)error @ aurelia-logging-console.js:62
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:3000/src/samples/grid/basic-use.html Array[1]
```

**3** Click on `Installation` menu item - ___you see the correct page___
**4** Now, click on `Components catalog` menu item  - ___you get to see the catalog just fine___

**Conclusion** transition from `About` page to `Components catalog` page fails.

Note that the app update mentioned in the first paragraph fixes https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/397

**Comment by JeroenVinke** [comment]
I had this issue with the splitter control. The tabstrip seems to have the same "problem".

When you destroy the tabstrip, it will destroy any kendo widget that the tabstrip contains automatically. So that means that when we destroy any child kendo widget on `detached()` it will be destroyed for the second time if that control is in a tabstrip/splitter. So one way I found to check if the control is destroyed or not is to check the `element` property on the widget.

**Comment by adriatic** [comment]
My bad - should not have reopened this.
