### ISSUE TITLE
Bundeling doesnt work

### ISSUE THREAD

**Issue by alexsurg** [aurelia-ui-toolkits/aurelia-kendoui-bridge#404]
Hi,

I just tried to add the bridge to my bundle but i get but i get the following exception

```
Error on fetch for npm:aurelia-kendoui-bridge@0.5.0/aurelia-kendoui-bridge.d.ts at file:///D:/tfs/McKesson/MCOngoing/WPL/Site/jspm_packages/npm/aurelia-kendoui-bridge@0.5.0/aurelia-kendoui-bridge.d.ts
	TypeError: Cannot read property 'substr' of undefined
    at fromFileURL (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\lib\utils.js:58:13)
    at SystemJSNodeLoader.<anonymous> (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\aurelia-bundler\dist\bundler.js:79:86)
    at SystemJSNodeLoader.loader.fetch (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\lib\builder.js:172:59)
    at D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\lib\trace.js:378:23
    at tryCatcher (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:676:18)
    at Async._drainQueue (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\tfs\McKesson\MCOngoing\WPL\Site\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I added the bridge to the bundle in the following way:

```
"[aurelia-kendoui-bridge]",
"[aurelia-kendoui-bridge/**/*]",
"aurelia-kendoui-bridge/**/*.html!text"
```

Do you have any idea why i get this error

Thanks,
Alex

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/bundler/issues/90#issuecomment-190375790 seems like a similar issue and a fix has been mentioned there. Can you try that out?

**Comment by alexsurg** [comment]
Hi,
Regarding the fix that you suggested, i already had this configuration in my bundle.
I have updated the aurelia bundler to 0.3.2 and JSPM to 0.16.29 to see if it will fix the issue.
Now instead of the previous exception i get the following:

```
[14:30:42] Error on translate for npm:aurelia-kendoui-bridge@0.5.0/aurelia-kendoui-bridge.d.ts at file:///Site/jspm_packages/npm/aurelia-kendoui-bridge@0.5.0/aurelia-kendoui-bridge.d.ts
	SyntaxError: file:///my local path/Site/jspm_packages/npm/aurelia-kendoui-bridge@0.5.0/aurelia-kendoui-bridge.d.ts: Unexpected token (2:9)
  1 | declare module 'aurelia-kendoui-bridge' {
> 2 |   import * as LogManager from 'aurelia-logging';
    |          ^
  3 |   import 'jquery';
  4 |   import 'kendo.autocomplete.min';
  5 |   import 'kendo.virtuallist.min';
```

I tried to remove the first import of the log to see if it will work but it throws the same exception on the jquery import.

Can you please check this issue and see if you can bundle with my versions.

Thanks,

**Comment by JeroenVinke** [comment]
Make sure that you only use jspm 0.16.15 when using aurelia for the time being. 

With jspm 0.16.15 and aurelia bundler 0.3.2 and [this configuration](https://github.com/aurelia-ui-toolkits/demo-kendo/blob/master/build/bundles.js#L30-L32) it works for me. If it still doesn't work, please share your bundle configuration.

**Comment by JeroenVinke** [comment]
I noticed that it tries to bundle the typescript definition `d.ts` while it should only bundle javascript and html files, so something is off here

**Comment by alexsurg** [comment]
Thanks, after looking at the configuration file and your comment about the `d.ts` i found the issue.
I took the bundle settings from your help docs: http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/bridge_developers_notes/5._on_bundling
It said their to set the bundle like this:
```
"src/app-build": {
      "includes": [
        "[*.js]",
        "[aurelia-kendoui-bridge]",
        "[aurelia-kendoui-bridge/**/*]",
        "aurelia-kendoui-bridge/**/*.html!text",
      ]
    },
```
but in the configuration file it is different:
`"[aurelia-kendoui-bridge/**/*.js]",`

I didnt saw that ".js" is missing, after i added it the bundle started to work.
Please fix it in your docs.

**Comment by JeroenVinke** [comment]
Will do :+1:
