### ISSUE TITLE
Demo not working in IE

### ISSUE THREAD

**Issue by henning-krause** [aurelia-ui-toolkits/aurelia-kendoui-bridge#441]
The Demo on http://aurelia-ui-toolkits.github.io/demo-kendo does not run on Internet Explorer 11.

The relevant portion from the console:
INFO [aurelia] Aurelia Started
Potentially unhandled rejection [1] TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (Unknown script code:64:31816)
   at each (Unknown script code:1:23859)
   at Z.prototype.each (Unknown script code:1:21834)
   at value (Unknown script code:64:31778)
   at value (Unknown script code:64:30678)
   at Anonymous function (Unknown script code:65:399)
   at M (http://aurelia-ui-toolkits.github.io/demo-kendo/jspm_packages/system-polyfills.js:4:8723)
   at H (http://aurelia-ui-toolkits.github.io/demo-kendo/jspm_packages/system-polyfills.js:4:8310)
   at R.prototype.when (http://aurelia-ui-toolkits.github.io/demo-kendo/jspm_packages/system-polyfills.js:4:12042)
   at b.prototype.run (http://aurelia-ui-toolkits.github.io/demo-kendo/jspm_packages/system-polyfills.js:4:11076)

Is there a polyfill missing?

**Comment by JeroenVinke** [comment]
When I added core-js back I got this error: https://github.com/aurelia/framework/issues/373

**Comment by smccrea** [comment]
I ran across this recently. IE is missing the polyfill for string.includes (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes) which is used in the theme-manager.js `if (this.href.includes('styles/kendo.')`

**Comment by JeroenVinke** [comment]
@smccrea thanks, that fixed the error mentioned in this issue.

But I still got this error: https://github.com/aurelia/framework/issues/373. I updated to babel6 but then saw that this error is thrown because systemjs is doing on the fly tranpilation. So I updated the babel-runtime to babel6 but then I got a couple of new errors in all browsers and I have no idea how to fix them. 

So I would recommend to wait for Aurelia to make their bundler compatible with JSPM 0.17 and then try this again..
