### ISSUE TITLE
Catalog app's help page crashes

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#468]
Catalog version 0.8.0

Click on the Help menu right after the app starts (or anytime after) - you get:

```
app-build-40c9cfa6bb.js:20ERROR [app-router] Error: Unexpected token ] in JSON at position 779
	Error loading http://aurelia-ui-toolkits.github.io/demo-kendo/src/help/registry.json!http…ts.github.io/demo-kendo/jspm_packages/github/systemjs/plugin-json@0.1.1.js as "./registry.json!" from http://aurelia-ui-toolkits.github.io/demo-kendo/src/help/doc.js
    at Object.parse (native)
    at l.define.instantiate (http://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-40c9cfa6bb.js:1:9634)
    at l.instantiate (http://aurelia-ui-toolkits.github.io/demo-kendo/jspm_packages/system.js:5:16214)
    at http://aurelia-ui-toolkits.github.io/demo-kendo/jspm_packages/system.js:4:5994
    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:31:6820)
    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:12229)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13032)
    at r._settlePromise0 (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13733)
    at r._settlePromises (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:15063)
    at r._drainQueue (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:29:2941)
    at r._drainQueues (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:29:3002)
    at drainQueues (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:29:1213)
    at MutationObserver.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:28770)
```

**Comment by adriatic** [comment]
As I do not know what did you do since my last push to master and because there is no 0.8.0 release anywhere (probably the code is on your machine), I tried to see what happens if I clone the current master. It exhibits the same behavior as the current catalog app (also showing version 0.8.0).

I am pretty sure that this is caused by switching to babel 6 (did not really verify whether you did the switch to babel6) and using [this version of browser-sync ](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/package.json#L68)

**Comment by JeroenVinke** [comment]
Fixed.

> As I do not know what did you do since my last push to master and because there is no 0.8.0 release anywhere (probably the code is on your machine), I tried to see what happens if I clone the current master. It exhibits the same behavior as the current catalog app (also showing version 0.8.0).

> I am pretty sure that this is caused by switching to babel 6 (did not really verify whether you did the switch to babel6) and using this version of browser-sync

As (vaguely) mentioned in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/441#issuecomment-213420563 I did not successfully convert both the plugin and the SystemJS transpiler to babel6, so I did not went along with that change.
