### ISSUE TITLE
Kendo Grid Issues

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#559]
Gist: https://gist.run/?id=b73d7efea4024e442840eac3805429c2

Issues:

1. Custom Column - Combobox -- Cannot get the Id on the Id column:

       i. when  `k-field="category"`, then the selected id appears in while creating and saving new record `{"category":1,"categoryId":""}`.
       ii. when  `k-field="categoryId"`, then the selected id appears in while creating and saving new record `{"category":"","categoryId":1}`. However, when edit button is clicked, the dropdown values are not selected by default.

2. After creating a record, how to refresh grid?

Any help is appreciated in this matter.

**Comment by adriatic** [comment]
Are you aware that running your gist results with this stack trace
```
INFO [aurelia] Aurelia Started
undefined:1 Uncaught (in promise) Error: https://gist.host/run/1468345728421/app.js: Unexpected token (24:48)

  categoryComboboxEditor(container, options) {
    list=[{name:"aaa", id:1}, {name:"bbb", id:2}}]
    $('<input required data-text-field="CategoryName" data-value-field="CategoryID" data-bind="value:' + options.field + '"/>')
    .appendTo(container)
    .kendoComboBox({
	Error loading https://gist.host/run/1468345728421/app.js
    at Parser.pp.raise (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:64054:13)
    at Parser.pp.unexpected (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:65284:8)
    at Parser.pp.expect (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:65278:33)
    at Parser.pp.parseExprList (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:63867:12)
    at Parser.pp.parseExprAtom (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:63469:28)
    at Parser.parseExprAtom (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:66699:22)
    at Parser.pp.parseExprSubscripts (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:63318:19)
    at Parser.pp.parseMaybeUnary (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:63299:19)
    at Parser.pp.parseExprOps (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:63245:19)
    at Parser.pp.parseMaybeConditional (https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.19/jspm_packages/npm/babel-core@5.8.38/browser.js:63227:19)
```

Specifically: `app.js: Unexpected token (24:48)`

suggests that your `app.js` has some unexpected text in line 24, column 48

**Comment by genericuser-me** [comment]
My bad! updated the Gist

https://gist.run/?id=b73d7efea4024e442840eac3805429c2

**Comment by JeroenVinke** [comment]
if https://gist.run/?id=b33f377020fed844ab2c74834e9a6efa is not what you are looking for then i'm out of ideas

**Comment by genericuser-me** [comment]
This is exactly what I was saying, when we put `k-field="categoryId"` , and click on edit, the value is NOT selected by default in the dropdown.

e.g., we edit Chai , Condiments, Condiments is not selected in the combobox by default.


when we put `k-field="category"` , and click on edit, the value is selected by default in the dropdown. but the id field doesnt get the value.

I hope I am able to explain the problem better.

**Comment by JeroenVinke** [comment]
well, condiments is not selected because that row has no category ID defined in the JSON. I have updated the gist: https://gist.run/?id=b33f377020fed844ab2c74834e9a6efa so that that row has a category

**Comment by JeroenVinke** [comment]
defaults only apply for new records, not existing ones

**Comment by genericuser-me** [comment]
Can you please take a look at this, why it doesnt work here?

https://gist.run/?id=b73d7efea4024e442840eac3805429c2

**Comment by JeroenVinke** [comment]
@genericuser-me so because you are using `k-field="CategoryID"` now instead of `k-field="Category"`  the autocomplete will change the `CategoryID` of the row. The matching `Category` will not be looked up automatically, so you need additional code to look up the selected category.

Before doing anything, a row looks like this:
```
{
   Name:  "Chang",
   Category: {
      CategoryID: 1,
      CategoryName: "Beverages"
   },
   CategoryID: 1
}
```

After changing the category, the object looks like this:
```
{
   Name:  "Chang",
   Category: {
      CategoryID: 1,
      CategoryName: "Beverages"
   },
   CategoryID: 2
}
```

Note that the CategoryID has changed, but the Category is still the same. So you need to fix that.

I'd like to stress the fact that we are not providing Kendo support, that we are not Kendo experts and that we have to look into these things just as much as anyone else. If we were to help out with every Kendo issue then we would have no time left to do anything else. So please take into consideration that we have limited resources available to help people by asking questions related to the function of Kendo controls on the [kendo forums](http://www.telerik.com/forums/kendo-ui).

**Comment by genericuser-me** [comment]
Sure I understand that. Thanks so much for all your time and efforts
