### ISSUE TITLE
Error when using k-format on date time field.

### ISSUE THREAD

**Issue by brandonseydel** [aurelia-ui-toolkits/aurelia-kendoui-bridge#563]
```TypeScript
        this.datasource = new kendo.data.DataSource({
            batch: false,            
            transport: {
                read: (options) => {
                    this.intakeSearch.page = this.datasource.page();
                    this.intakeSearch.pageSize = this.datasource.pageSize();
                    this.intakeService.read(this.intakeSearch).then(data => {                        
                        options.success(data.content);
                    }).catch(error => {
                        this.events.publish('message', {
                            type: 'danger',
                            header: 'Error',
                            body: 'There was an error searching for intakes.  Please try again.'
                        });
                    })
                }
            },
            schema: {
                total: "total",
                data: "items",
                model: {
                    id: 'intakeId',
                    fields: {
                        dateTaken: { type: 'date'},
                        disposition: { type: 'string' },
                        assignedTo: { type: 'string' },
                        name: { type: 'string' },
                        phone: { type: 'string' },
                        referredBy: { type: 'string'},
                        takenBy: { type: 'string'},
                    }

                }
            },
            serverPaging: true,
            pageSize: this.currentPageSize
        });
```

```HTML
<ak-grid id="intakeSearchGrid"
                         k-data-source.bind="datasource"
                         k-pageable.bind="{ input: true, numeric: false}"
                         k-filterable.bind="true"
                         k-sortable.bind="true"
                         k-scrollable.bind="true"
                         k-selectable.bind="true"
                         k-selectable="row"
                         k-auto-bind="false"
                         k-widget.bind="grid"
                         k-editable="popup"
                         k-navigatable.bind="true"
                         k-on-change.delegate="select($event)"
                         k-on-cancel.delegate="cancel($event)">
                    <ak-col k-field="dateTaken" k-title="Date Taken" k-format.bind="{0:MM/dd/yyyy}"></ak-col>
                    <ak-col k-field="disposition" k-title="Disposition"></ak-col>
                    <ak-col k-field="assignedTo" k-title="Assigned To"></ak-col>
                    <ak-col k-field="name" k-title="Name"></ak-col>
                    <ak-col k-field="phone" k-title="Phone"></ak-col>
                    <ak-col k-field="referredBy" k-title="Referred By"></ak-col>
                    <ak-col k-field="takenBy" k-title="Taken By"></ak-col>
                </ak-grid>

```

Uncaught (in promise) TypeError: k.replace is not a function
    at init._cellTmpl (https://localhost:44378/dist/kendo-bridge.js:28:19081)
    at init._tmpl (https://localhost:44378/dist/kendo-bridge.js:28:18123)
    at init._templates (https://localhost:44378/dist/kendo-bridge.js:28:19759)
    at new init (https://localhost:44378/dist/kendo-bridge.js:26:19641)
    at HTMLDivElement.<anonymous> (https://localhost:44378/dist/kendo-bridge.js:87:6650)
    at Function.each (https://localhost:44378/dist/kendo-bridge.js:31:8489)
    at E.each (https://localhost:44378/dist/kendo-bridge.js:31:6456)
    at E.a.fn.(anonymous function) [as kendoGrid] (https://localhost:44378/dist/kendo-bridge.js:87:6627)
    at a.WidgetBase.a._createWidget (https://localhost:44378/dist/kendo-bridge.js:79:26514)
    at a.WidgetBase.a.createWidget (https://localhost:44378/dist/kendo-bridge.js:79:25993)_cellTmpl @ kendo-bridge.js:28_tmpl @ kendo-bridge.js:28_templates @ kendo-bridge.js:28init @ kendo-bridge.js:26(anonymous function) @ kendo-bridge.js:87each @ kendo-bridge.js:31each @ kendo-bridge.js:31a.fn.(anonymous function) @ kendo-bridge.js:87a.WidgetBase.a._createWidget @ kendo-bridge.js:79a.WidgetBase.a.createWidget @ kendo-bridge.js:79a.Grid.a.recreate @ kendo-bridge.js:29a.Grid.a.attached @ kendo-bridge.js:29a.Controller.a.attached @ aurelia.js:12a.View.a.attached @ aurelia.js:11a.ViewSlot.a.add @ aurelia.js:11(anonymous function) @ aurelia.js:8

**Comment by JeroenVinke** [comment]
Hey @brandonseydel 

The `.bind` part in `k-format.bind="{0:MM/dd/yyyy}"` is telling aurelia to parse `{0:MM/dd/yyyy}` which is not a valid object syntax. If you remove `.bind` then aurelia takes it as a string, which is what you want. [This](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html#binding) document contains more information about when to use `.bind`. Also see [this sample](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/binding-to-remote-data) where k-format is being used successfully.

**Comment by brandonseydel** [comment]
Wow that was a slip just kept looking past the .bind....
