### ISSUE TITLE
catalog app fails to start (master branch)

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#575]
I created the new branch locally (links-to-books) with the intent to fix the bad links - and started by rebuilding the bridge. First I deleted all jspm_packages and node_modules in both plugin and app folder and then rebuilt both.

`gulp watch` resulted with:

```
DEBUG [aurelia] Loading plugin aurelia-kendoui-bridge.
bluebird.min.js:29 Unhandled rejection ReferenceError: key is not defined
    at Array.setters (http://localhost:3000/src/aurelia-kendoui-bridge/index.js:17:35)
    at http://localhost:3000/jspm_packages/system.js:4:30583
    at execute (http://localhost:3000/src/aurelia-kendoui-bridge/common/decorators.js:56:7)
    at u (http://localhost:3000/jspm_packages/system.js:5:97)
    at u (http://localhost:3000/jspm_packages/system.js:5:32)
    at Object.execute (http://localhost:3000/jspm_packages/system.js:5:3188)
    at y (http://localhost:3000/jspm_packages/system.js:4:9948)
    at w (http://localhost:3000/jspm_packages/system.js:4:10327)
    at p (http://localhost:3000/jspm_packages/system.js:4:8205)
    at h (http://localhost:3000/jspm_packages/system.js:4:8590)
    at http://localhost:3000/jspm_packages/system.js:4:6896
    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:31:7722)
    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13014)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13817)
    at r._settlePromise0 (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:14518)
    at r._settlePromises (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:15848)
    at r._fulfill (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:14889)
    at a._resolve (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:19303)
    at a._promiseFulfilled (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:19650)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13919)
```

Master branch at the time I made the the previous `user-installable-sdk`  branch behaved fine, so I am not sure why does it misbehave now. Too late for me to srat digging into this, sorry

**Comment by JeroenVinke** [comment]
i'll be damned, no clue why this happened all of a sudden. [this fixed it](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/070799b68ea833a48759cbb2f849accb5c8628b8). Somehow when you `export *` the loop generated by babel-runtime/systemjs contains a syntax error (references `key` while the variable is called `_key`)

![image](https://cloud.githubusercontent.com/assets/2189477/17093411/769704b0-5249-11e6-8fb4-aa8feecad5a0.png)

tried to go back to an older babel-runtime but it didn't fix it. The code used by our users is correct though, as that is transpiled with babel 6 (not babel 5 which we can't get rid of until jspm 0.17)

**Comment by adriatic** [comment]
I would rather pretend that I did not see this explanation as it completely shakes my confidence in our building process. What kind of a bug could cause the replacement of `_key` into `key` in the middle of the loop????

**Comment by adriatic** [comment]
Confirming the fix by rebuilding the app locally

**Comment by adriatic** [comment]
So, you think that this was not one time exceptional behavior?

**Comment by JeroenVinke** [comment]
Yeah think this may be related to babel 5 (most are on babel 6)
