### ISSUE TITLE
running list of bugs discovered in creating the bridge architecture book

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#581]
-  [x] Drag and Drop sample crashes
```
aurelia-logging-console.js:54 ERROR [app-router] Error: Route not found: drag-and-drop
    at Router._createNavigationInstruction (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:1039:29)
    at http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:1462:28
    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:31:7722)
    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13014)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13817)
    at r._settlePromise0 (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:14518)
    at r._settlePromises (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:15848)
    at r._drainQueue (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:29:3148)
    at r._drainQueues (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:29:3209)
    at drainQueues (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:29:1238)
```

**Comment by adriatic** [comment]
This process is continuing ...

**Comment by JeroenVinke** [comment]
I will go through all samples and confirm that they are working
