### ISSUE TITLE
improve webpack kendo-core config

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#588]
:point_up: [August 2, 2016 10:09 PM](https://gitter.im/adriatic/Aurelia-KendoUI?at=57a0fdf50bd017c16e36424e)

**Comment by JeroenVinke** [comment]
Here are some things to look into:

> Here are some conclusions of the test I made to port the working jspm app to aurelia cli using the bridge.

Importing kendo-core does not work via

```
{
    "name": "kendo-ui-core",
    "path": "../node_modules/kendo-ui-core"
}
```
with `error /phantom/js/aurelia/rhapsody.v1/node-modules/kendo-ui-core.js` at bundling time (au build)

```
{
    "name": "kendo-ui-core",
    "path": "../node_modules/kendo-ui-core",
    "main": "js/kendo.core"
}
```
passes the bundling part but fails when the application start:

```
vendor-bundle.js:11973 ERROR [app-router] Error: Error invoking Menu. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: The kendo control 'kendoMenu' is not available. Did you load this control?
Inner Error Stack:
Error: The kendo control 'kendoMenu' is not available. Did you load this control?
    at WidgetBase.control (http://localhost:8080/diapason/rhapsody/node_modules/aurelia-kendoui-bridge/dist/amd/common/widget-base.js:54:15)
    at new Menu (http://localhost:8080/diapason/rhapsody/node_modules/aurelia-kendoui-bridge/dist/amd/menu/menu.js:22:36)
```

by looking in the bundle the kendo.menu.js is not bundled and no http request to load it is done.

Importing a trial via vendors

```
{
    "name": "kendo",
    "path": "../vendors",
    "main": "js/kendo.all.min"
}
```
is bundled but fails at runtime with:

```
Unhandled rejection ReferenceError: kendo is not defined
    at ControlProperties.getWidgetProperties (http://localhost:8080/diapason/rhapsody/scripts/vendor-bundle.js:35448:11)
    at ControlProperties.getProperties (http://localhost:8080/diapason/rhapsody/scripts/vendor-bundle.js:35423:27)
    at http://localhost:8080/diapason/rhapsody/scripts/vendor-bundle.js:35347:42
    at Object.<anonymous> (http://localhost:8080/diapason/rhapsody/node_modules/aurelia-kendoui-bridge/dist/amd/toolbar/toolbar-item-button.js:17:322)
```

The only thing that works with the trial is to add directly to index.html:

```
<script src="vendors/js/jquery.min.js"></script>
<script src="vendors/js/kendo.all.min.js"></script>
```

Please note that this method does not allow to import any kendo part via:

```
import 'kendo/js/kendo.button';
```

because the cli bundler parses the imports:

```
{ uid: 10,
  name: 'writeBundles',
  branch: false,
  error: 
   { [Error: ENOENT: no such file or directory, open '/phantom/js/aurelia/rhapsody.v1/src/kendo/js/kendo.button.js']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/phantom/js/aurelia/rhapsody.v1/src/kendo/js/kendo.button.js',
     moduleTree: [ 'main' ],
     fileName: '/phantom/js/aurelia/rhapsody.v1/src/main.js' },
  duration: [ 0, 333397969 ],
  time: 1470320286792 }
...
```

Also in this approach I am not able to call `data(...)` such as:

```
let tabstrip = $("#loaded-modules").data("kendoTabStrip");
```

tabstrip is undefined. Cannot asses what causes this problem.

The bridge itself can be bundled via:

```
{
	"name": "aurelia-kendoui-bridge",
	"path": "../node_modules/aurelia-kendoui-bridge/dist/amd",
	"main": "index"
}
```
however all components are loaded via direct requests (and not bundled) thus it is needed to copy the node folder into the deployment, otherwise using a component will fail (since the cli does not parses requires)

```
return gulp.src(['index.html', 'favicon.ico', 'scripts/**', 'lib/**', 'locales/**', 'node_modules/aurelia-kendoui-bridge/**', 'node_modules/bootstrap/**', 'src/dynamic/**'], { base: "." })
    .pipe(gulp.dest(deployDir));
```

**Comment by JeroenVinke** [comment]
:point_up: [August 8, 2016 8:13 PM](https://gitter.im/adriatic/Aurelia-KendoUI?at=57a8cbc046610f1739493e70)
