### ISSUE TITLE
Catalog app for KendoUI Bridge beta fails to run grid

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#593]
It could be that my machine (which saw nodejs for the first time this evening) might be off somehow, but it is not likely. I clicked on the `grid` button and got

```
DEBUG [templating] importing resources for http://gist-serve.jeroenvinke.nl/file-cache-bust/32734/7629847ee2d5b90d7f84925121f90345/app.html Array[0]
:3000/jspm_packages/npm/aurelia-logging-console@1.0.0-rc.1.0.0/aurelia-logging-console.js:54 ERROR [app-router] TypeError: links.forEach is not a function(…)error @ :3000/jspm_packages/npm/aurelia-logging-console@1.0.0-rc.1.0.0/aurelia-logging-console.js:54
:3000/jspm_packages/npm/aurelia-logging-console@1.0.0-rc.1.0.0/aurelia-logging-console.js:54 ERROR [app-router] TypeError: links.forEach is not a function(…)error @ :3000/jspm_packages/npm/aurelia-logging-console@1.0.0-rc.1.0.0/aurelia-logging-console.js:54
:3000/jspm_packages/npm/aurelia-logging-console@1.0.0-rc.1.0.0/aurelia-logging-console.js:54 ERROR [app-router] TypeError: links.forEach is not a function(…)error @ :3000/jspm_packages/npm/aurelia-logging-console@1.0.0-rc.1.0.0/aurelia-logging-console.js:54
```

**Comment by adriatic** [comment]
I am also seeing problems with "unloading css": `TypeError: links.forEach is not a function`

```
 at SampleRunner.unloadSampleCSS (http://localhost:3000/src/samples/sample-runner.js!transpiled:165:19)
    at SampleRunner.deactivate (http://localhost:3000/src/samples/sample-runner.js!transpiled:158:18)
    at iterate (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:1169:48)
    at processDeactivatable (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:1179:12)
    at DeactivatePreviousStep.run (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:1135:14)
    at next (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:179:20)
    at iterate (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:1263:14)
    at processActivatable (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:1266:12)
    at CanActivateNextStep.run (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:1123:14)
    at next (http://localhost:3000/jspm_packages/npm/aurelia-router@1.0.0-rc.1.0.1/aurelia-router.js:179:20)
    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:31:7722)
    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13014)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13817)
    at r._settlePromise0 (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:14518)
    at r._settlePromises (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:15848)
    at r._fulfill (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:14889)error @ aurelia-logging-console.js:54log @ aurelia-logging.js:37error @ aurelia-logging.js:70processResult @ aurelia-router.js:1787(anonymous function) @ aurelia-router.js:1740r @ bluebird.min.js:31r._settlePromiseFromHandler @ bluebird.min.js:30r._settlePromise @ bluebird.min.js:30r._settlePromise0 @ bluebird.min.js:30r._settlePromises @ bluebird.min.js:30r._fulfill @ bluebird.min.js:30r._settlePromise @ bluebird.min.js:30r._settlePromise0 @ bluebird.min.js:30r._settlePromises @ bluebird.min.js:30r._fulfill @ bluebird.min.js:30r._settlePromise @ bluebird.min.js:30r._settlePromise0 @ bluebird.min.js:30r._settlePromises @ bluebird.min.js:30r._fulfill @ bluebird.min.js:30r._resolveCallback @ bluebird.min.js:30r._settlePromiseFromHandler @ bluebird.min.js:30r._settlePromise @ bluebird.min.js:30r._settlePromise0 @ bluebird.min.js:30r._settlePromises @ bluebird.min.js:30r._fulfill @ bluebird.min.js:30a._resolve @ bluebird.min.js:30a._promiseFulfilled @ bluebird.min.js:30r._settlePromise @ bluebird.min.js:30r._settlePromise0 @ bluebird.min.js:30r._settlePromises @ bluebird.min.js:30r._drainQueue @ bluebird.min.js:29r._drainQueues @ bluebird.min.js:29drainQueues @ bluebird.min.js:29
```
