### ISSUE TITLE
Error when setting up aurelia-kendo-bridge beta with vanilla Aurelia CLI project

### ISSUE THREAD

**Issue by prsmith1** [aurelia-ui-toolkits/aurelia-kendoui-bridge#630]
Hi,

I have set up a new Aurelia project using the CLI, 'au new' command. I have then set-up a kendo-sdk folder with the js and styles subfolders and all the kendo files within. I have gone through the instructions on the following page:

https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/installation 

Meaning: 

npm install aurelia-kendoui-bridge@1.0.0-beta.1.0.13

adding the following to index.html:

   <script src="kendo-sdk/js/jquery.min.js"></script>
   <script src="kendo-sdk/js/kendo.all.min.js"></script>
 <link rel="stylesheet" href="kendo-sdk/styles/kendo.common.min.css">
 <link rel="stylesheet" href="kendo-sdk/styles/kendo.bootstrap.min.css">

...and changing the files as per the aurelia-cli page.

This seems to build and run file, but when I put kendo controls in the app.html page they do not render as kendo controls. So I have tried adding the following to the top of the app.html

  <require from="aurelia-kendooui-bridge/button/button"></require>
<require from="aurelia-kendooui-bridge/datetimepicker/datetimepicker"></require>

I am now getting the following error:

Unhandled rejection Error: Script error for "aurelia-kendooui-bridge/button/button"
http://requirejs.org/docs/errors.html#scripterror
    at Error (native)
    at F (http://localhost:9000/scripts/vendor-bundle.js:3763:290)
    at HTMLScriptElement.onScriptError (http://localhost:9000/scripts/vendor-bundle.js:3786:113)
From previous event:
    at DefaultLoader.loadModule (http://localhost:9000/scripts/vendor-bundle.js:11795:14)
    at DefaultLoader.loadAllModules (http://localhost:9000/scripts/vendor-bundle.js:11742:25)
    at ViewEngine.importViewResources (http://localhost:9000/scripts/vendor-bundle.js:19678:26)
    at ViewEngine.loadTemplateResources (http://localhost:9000/scripts/vendor-bundle.js:19648:19)
    at http://localhost:9000/scripts/vendor-bundle.js:19596:41
From previous event:
    at ViewEngine.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:19580:67)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:17000:25)
    at HtmlBehaviorResource.load (http://localhost:9000/scripts/vendor-bundle.js:20333:29)
    at http://localhost:9000/scripts/vendor-bundle.js:20866:18
From previous event:
    at CompositionEngine.createController (http://localhost:9000/scripts/vendor-bundle.js:20854:71)
    at CompositionEngine._createControllerAndSwap (http://localhost:9000/scripts/vendor-bundle.js:20833:19)
    at CompositionEngine.compose (http://localhost:9000/scripts/vendor-bundle.js:20913:21)
    at TemplatingEngine.compose (http://localhost:9000/scripts/vendor-bundle.js:21177:38)
    at Aurelia.setRoot (http://localhost:9000/scripts/vendor-bundle.js:10768:21)
    at http://localhost:9000/scripts/app-bundle.js:75:22
From previous event:
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:74:21)
    at http://localhost:9000/scripts/vendor-bundle.js:4291:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:4290:48)
    at handleApp (http://localhost:9000/scripts/vendor-bundle.js:4281:12)
    at http://localhost:9000/scripts/vendor-bundle.js:4310:13
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:4308:40
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:4307:29
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:4303:26)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4330:3)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:3785:299)
    at Object.check (http://localhost:9000/scripts/vendor-bundle.js:3774:50)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3779:58)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3783:433)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:3778:436)
    at http://localhost:9000/scripts/vendor-bundle.js:3763:140
    at y (http://localhost:9000/scripts/vendor-bundle.js:3762:207)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3777:469)
    at Object.init (http://localhost:9000/scripts/vendor-bundle.js:3772:154)
    at http://localhost:9000/scripts/vendor-bundle.js:3782:308

for ref my app.html page is this:

<template>
  <require from="aurelia-kendooui-bridge/grid/grid"></require>
  <require from="aurelia-kendooui-bridge/button/button"></require>
  <h1>${message}</h1>
  <button k-button="k-icon: ungroup; k-widget.bind: button" k-on-click.delegate="test()">Kendo UI Button</button>

            <input ak-datetimepicker="k-value.bind: today"/>
</template>

my app.js is:

export class App {
  constructor() {
    this.message = 'Hello World!';
    this.today = Date();
  }

  test() {
    debugger;
    alert('You clicked me');
  }
}

I am still getting my head around how everything should work together with the aurelia cli project, kendo bridge beta, etc. so am 'flying blind' a bit as it were! Can anybody think of what I may have missed?

Thanks,
Piers

**Comment by JeroenVinke** [comment]
Hi, it looks like a typo: `aurelia-kendooui-bridge/button/button`. In the top right corner of every sample there is an "Imports" button that displays the `<require>` statements you need: https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/datepicker-basic-usage. I see that you have been trying to use `ak-datetimepicker`, so you would need `<require from="aurelia-kendoui-bridge/datetimepicker/datetimepicker"></require>`

**Comment by prsmith1** [comment]
Thanks - that fixed it. Can't believe it was just that!

I'm now trying to get the basic grid working as per https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/grid-basic-use but it doesn't seem to like: <require from="./app.css!css"></require>

It seems to be looking for http://localhost:9000/src/app.css.js and I get: vendor-bundle.js:3763 Uncaught Error: Script error for "app.css", needed by: app.css!css_unnormalized4

Any ideas?

**Comment by JeroenVinke** [comment]
Great!

It is trying to load `app.css`, because of `<require from="./app.css!css"></require>`. The `!css` part is something specific to the JSPM module loader, and since aurelia-cli uses RequireJS it fails. Try and replace it with `<require from="./app.css"></require>`, although the only thing in `app.css` is for rendering the photo nicely in the basic use sample, so you may not need the `<require>` statement for `app.css` at all

[This sample](https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/grid-binding-to-remote-data) does not use any css files

**Comment by prsmith1** [comment]
Ah yes - I just had to change it to <require from="./app.css"></require> and it worked.

Thanks very much for your quick responses.
