### ISSUE TITLE
problem running kendo version of esnext-webpack version of skeleton navigations

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#680]
Summary - after making all the changes to the (initially working) **[skeleton-esnext-webpack](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack)** sample, needed to add the **[KendoUI autocomplete sample](https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/autocomplete-customizing-templates)**, this modified application fails with

![image](https://cloud.githubusercontent.com/assets/2712405/21772588/f44f0904-d659-11e6-816f-2e5bc7750b15.png)

```
...
aurelia-logging-console.js:54 ERROR [app-router] TypeError: Cannot read property 'fetch' of undefined
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost:9000/aurelia-bootstrap.bundle.js:15874:60)
    at WebpackLoader._import (http://localhost:9000/aurelia-bootstrap.bundle.js:15871:18)
    at WebpackLoader.loadModule (http://localhost:9000/aurelia-bootstrap.bundle.js:15929:17)
    at WebpackLoader.loadAllModules (http://localhost:9000/aurelia-bootstrap.bundle.js:15916:23)
    at ViewEngine.importViewResources (http://localhost:9000/aurelia.bundle.js:3253:24)
    at ViewEngine.loadTemplateResources (http://localhost:9000/aurelia.bundle.js:3223:17)
    at http://localhost:9000/aurelia.bundle.js:3171:39
From previous event:
    at ViewEngine.loadViewFactory (http://localhost:9000/aurelia.bundle.js:3155:65)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/aurelia.bundle.js:575:23)
    at HtmlBehaviorResource.load (http://localhost:9000/aurelia.bundle.js:3913:27)
    at RouterView.process (http://localhost:9000/aurelia.bundle.js:11901:21)
    at _loop (http://localhost:9000/aurelia.bundle.js:16267:29)
    at NavigationInstruction._commitChanges (http://localhost:9000/aurelia.bundle.js:16282:7)
    at CommitChangesStep.run (http://localhost:9000/aurelia.bundle.js:16134:34)
    at next (http://localhost:9000/aurelia.bundle.js:16103:18)
    at iterate (http://localhost:9000/aurelia.bundle.js:17213:12)
    at processActivatable (http://localhost:9000/aurelia.bundle.js:17216:10)
    at ActivateNextStep.run (http://localhost:9000/aurelia.bundle.js:17097:12)
    at next (http://localhost:9000/aurelia.bundle.js:16103:18)
    at iterate (http://localhost:9000/aurelia.bundle.js:17126:12)
    at processDeactivatable (http://localhost:9000/aurelia.bundle.js:17129:10)
    at DeactivatePreviousStep.run (http://localhost:9000/aurelia.bundle.js:17085:12)
    at next (http://localhost:9000/aurelia.bundle.js:16103:18)
    at iterate (http://localhost:9000/aurelia.bundle.js:17213:12)
    at processActivatable (http://localhost:9000/aurelia.bundle.js:17216:10)
...
```

This modified sample is here https://github.com/adriatic/kendo-tutorials/tree/master/webpack.

The whole process of modifying the original is described here:  https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/675#issuecomment-271185386

**Comment by adriatic** [comment]
My view of how to deal with this:

1. Run the sample to verify that this behavior is reproducible
2. If the app fails the same way, see if you can guess why by using Chrome debugger (this assumes Webpack experience of course, that I do not have)
3. If you cannot figure out what is wrong, please go through the steps I did (https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/675#issuecomment-271185386), verify that they match the [installation instructions](https://aurelia-ui-toolkits.gitbooks.io/kendo-ui-sdk-installation/content/) written by @JeroenVinke and see if I missed something.
4. If at this point there is no solution, I will file an issue with webpack

(Note: the steps 1, 2 and 3 above are your courteous help to save me from embarrassment of creating a silly pilot error)

**Comment by adriatic** [comment]
@JeroenVinke diagnosed with elegant ease - :point_up: [January 9, 2017 11:24 AM](https://gitter.im/aurelia-ui-toolkits/team?at=5873b94f6c1635643c06a2c3)

These two lines
```
  <require from="kendo-ui/styles/kendo.common.min.css!"></require>
  <require from="kendo-ui/styles/kendo.bootstrap.min.css!"></require>
```

should not be a part of the `autocomplete.html` file
