### ISSUE TITLE
typescript webpack kendo-core navigation skeleton fails

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#683]
Click on the added `Autocomplete` item crashes the app.

![image](https://cloud.githubusercontent.com/assets/2712405/21835449/0ebc3618-d78b-11e6-9434-50cbd45923ab.png)

The error `Template markup must be wrapped in a <template> element e.g. <template> <!-- markup here --> </template>` seems weird coming from the "webpack bundling code" (perhaps I just do not trust webpack :cry:

App lives [here](https://github.com/adriatic/kendo-tutorials/tree/master/typescript-webpack)

App creation log is [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/675#issuecomment-271679648)

***
**Details**
Chrome console:
```
aurelia-logging-console.js:54 ERROR [app-router] Error: Template markup must be wrapped in a <template> element e.g. <template> <!-- markup here --> </template>
    at Object.createTemplateFromMarkup (http://localhost:9000/aurelia-bootstrap.bundle.js:15639:13)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15041:40
From previous event:
    at TextTemplateLoader.loadTemplate (http://localhost:9000/aurelia-bootstrap.bundle.js:15040:43)
    at Object.fetch (http://localhost:9000/aurelia-bootstrap.bundle.js:15090:69)
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost:9000/aurelia-bootstrap.bundle.js:15143:61)
From previous event:
    at WebpackLoader._import (http://localhost:9000/aurelia-bootstrap.bundle.js:15140:18)
    at WebpackLoader.loadTemplate (http://localhost:9000/aurelia-bootstrap.bundle.js:15204:17)
    at ensureRegistryEntry (http://localhost:9000/aurelia.bundle.js:4441:17)
    at ViewEngine.loadViewFactory (http://localhost:9000/aurelia.bundle.js:4509:12)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/aurelia.bundle.js:1913:23)
    at HtmlBehaviorResource.load (http://localhost:9000/aurelia.bundle.js:5274:27)
    at RouterView.process (http://localhost:9000/aurelia.bundle.js:13262:21)
    at _loop (http://localhost:9000/aurelia.bundle.js:16290:29)
    at NavigationInstruction._commitChanges (http://localhost:9000/aurelia.bundle.js:16305:7)
    at CommitChangesStep.run (http://localhost:9000/aurelia.bundle.js:16157:34)
    at next (http://localhost:9000/aurelia.bundle.js:16126:18)
    at iterate (http://localhost:9000/aurelia.bundle.js:17236:12)
    at processActivatable (http://localhost:9000/aurelia.bundle.js:17239:10)
    at ActivateNextStep.run (http://localhost:9000/aurelia.bundle.js:17120:12)
    at next (http://localhost:9000/aurelia.bundle.js:16126:18)
    at iterate (http://localhost:9000/aurelia.bundle.js:17149:12)
    at processDeactivatable (http://localhost:9000/aurelia.bundle.js:17152:10)
    at DeactivatePreviousStep.run (http://localhost:9000/aurelia.bundle.js:17108:12)
From previous event:
    at LoadRouteStep.run (http://localhost:9000/aurelia.bundle.js:17383:66)
    at next (http://localhost:9000/aurelia.bundle.js:16126:18)
    at iterate (http://localhost:9000/aurelia.bundle.js:17149:12)
    at processDeactivatable (http://localhost:9000/aurelia.bundle.js:17152:10)
    at CanDeactivatePreviousStep.run (http://localhost:9000/aurelia.bundle.js:17084:12)
    at next (http://localhost:9000/aurelia.bundle.js:16126:18)
    at http://localhost:9000/aurelia.bundle.js:16575:14
From previous event:
    at BuildNavigationPlanStep.run (http://localhost:9000/aurelia.bundle.js:16573:56)
    at next (http://localhost:9000/aurelia.bundle.js:16126:18)
    at Pipeline.run (http://localhost:9000/aurelia.bundle.js:16139:12)
    at http://localhost:9000/aurelia.bundle.js:17712:23
From previous event:
    at AppRouter._dequeueInstruction (http://localhost:9000/aurelia.bundle.js:17685:30)
    at http://localhost:9000/aurelia.bundle.js:17676:15
From previous event:
    at AppRouter._queueInstruction (http://localhost:9000/aurelia.bundle.js:17673:12)
    at http://localhost:9000/aurelia.bundle.js:17607:22
From previous event:
    at AppRouter.loadUrl (http://localhost:9000/aurelia.bundle.js:17606:51)
    at BrowserHistory._loadUrl (http://localhost:9000/aurelia.bundle.js:15373:53)
    at BrowserHistory._checkUrl (http://localhost:9000/aurelia.bundle.js:15366:12)
error @ aurelia-logging-console.js:54
log @ aurelia-logging.js:36
error @ aurelia-logging.js:69
processResult @ aurelia-router.js:1767
(anonymous) @ aurelia-router.js:1720
tryCatcher @ bluebird.js:5215
Promise._settlePromiseFromHandler @ bluebird.js:3238
Promise._settlePromise @ bluebird.js:3295
Promise._settlePromise0 @ bluebird.js:3340
Promise._settlePromises @ bluebird.js:3419
Promise._fulfill @ bluebird.js:3364
Promise._settlePromise @ bluebird.js:3308
Promise._settlePromise0 @ bluebird.js:3340
Promise._settlePromises @ bluebird.js:3419
Promise._fulfill @ bluebird.js:3364
Promise._resolveCallback @ bluebird.js:3181
Promise._settlePromiseFromHandler @ bluebird.js:3250
Promise._settlePromise @ bluebird.js:3295
Promise._settlePromise0 @ bluebird.js:3340
Promise._settlePromises @ bluebird.js:3415
(anonymous) @ bluebird.js:175
(anonymous) @ bluebird.js:4469
```

**Comment by JeroenVinke** [comment]
The template tag [here](https://github.com/adriatic/kendo-tutorials/blob/master/typescript-webpack/src/autocomplete.html) is missing `<`

**Comment by adriatic** [comment]
Thank you - and never start selecting text from the top of the file 😏

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/21881951/b3de58e2-d8a8-11e6-8c09-621da22f4f12.png)

Works fine here, so it must be caching
