### ISSUE TITLE
The switch sample does not work

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-kendoui-bridge#739]
Nothing is displayed..
https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/switch-basic-use

There is a stacktrace in console output:

```
Unhandled rejection TypeError: Cannot read property 'off' of null
    at init.destroy (https://aurelia-ui-toolkits.github.io/demo-kendo/kendo-sdk/js/kendo.all.min.js:40:5125)
    at a.WidgetBase.a.destroy (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:10:4399)
    at a.DropDownList.a.destroy (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:5:23602)
    at a.DropDownList.a.detached (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:5:23662)
    at a.Controller.a.detached (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:54:2561)
    at a.View.a.detached (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:53:12706)
    at h (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:53:16005)
    at a.ViewSlot.a.removeAll (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:53:16147)
    at a.Compose.a.unbind (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:8:19755)
    at a.Controller.a.unbind (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:54:2125)
    at a.View.a.unbind (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:53:11781)
    at SampleRunner.detached (https://aurelia-ui-toolkits.github.io/demo-kendo/src/samples/sample-runner.js!transpiled:179:30)
    at a.Controller.a.detached (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:54:2561)
    at a.View.a.detached (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:53:12648)
    at h (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:53:16005)
    at a.ViewSlot.a.removeAll (https://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-72d795efe0.js:53:16147)
```

**Comment by adriatic** [comment]
Something is off (ought to be your machine's context) as this sample works fine on my machine. Also this would be a catalog (deno-kendo) issue -  not a part of https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues collection 😄 

![image](https://cloud.githubusercontent.com/assets/2712405/25283114/aa22a7f6-2680-11e7-898a-9780764b5867.png)

**Comment by Thanood** [comment]
Interesting, it's working now..! 😃 
I've always added bridge issues here, btw.
