### ISSUE TITLE
Error invoking ContextMenu after version upgrade

### ISSUE THREAD

**Issue by YaelHal** [aurelia-ui-toolkits/aurelia-kendoui-bridge#767]
Hi,
I'm using aurelia-kendoui-bridge and after Aurelia version upgrade I'm getting the following error message:

Inner Error:
Message: The kendo control 'kendoContextMenu' is not available. Did you load Kendo (in addition to the bridge)?
Inner Error Stack:
Error: The kendo control 'kendoContextMenu' is not available. Did you load Kendo (in addition to the bridge)?
    at WidgetBase.control (http://localhost:32433/jspm_packages/npm/aurelia-kendoui-bridge@1.6.4/common/widget-base.js:58:15)
    at new ContextMenu (http://localhost:32433/jspm_packages/npm/aurelia-kendoui-bridge@1.6.4/contextmenu/contextmenu.js:23:36)
    at Object.invoke (http://localhost:32433/jspm_packages/npm/aurelia-dependency-injection@1.3.1/aurelia-dependency-injection.js:448:14)
    at InvocationHandler.invoke (http://localhost:32433/jspm_packages/npm/aurelia-dependency-injection@1.3.1/aurelia-dependency-injection.js:413:168)
    at Container.invoke (http://localhost:32433/jspm_packages/npm/aurelia-dependency-injection@1.3.1/aurelia-dependency-injection.js:677:25)
    at ProviderResolver.get (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:2047:74)
    at Container.get (http://localhost:32433/jspm_packages/npm/aurelia-dependency-injection@1.3.1/aurelia-dependency-injection.js:616:23)
    at Container.elementContainerGet [as get] (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:2102:17)
    at HtmlBehaviorResource.create (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:4

Used the following in main.js:

.plugin('aurelia-kendoui-bridge', (kendo) => {    kendo.kendoGrid().kendoTreeView().kendoDatePicker().kendoContextMenu().kendoTooltip().kendoAutoComplete().kendoNumericTextBox().kendoProgressBar();

This used to work before the upgrade, I understand that something was changed as I read in here:
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/742

So what do I need to change ? how to load  Kendo?

**Comment by JeroenVinke** [comment]
Hi @YaelHal 

From what version did you update?

**Comment by YaelHal** [comment]
aurelia-kendoui-bridge from 0.12.2 to 1.6.4
aurelia-dependency-injection from 1.0.0 to 1.3.1
aurelia-templating from 1.1.0 to 1.4.2

**Comment by JeroenVinke** [comment]
You need both, 

```
(kendo) => { kendo.kendoGrid().kendoTreeView().kendoDatePicker().kendoContextMenu().kendoTooltip().kendoAutoComplete().kendoNumericTextBox().kendoProgressBar();
```

This loads the aurelia-kendoui-bridge wrappers, but not the Kendo controls. An import statement would do that

**Comment by YaelHal** [comment]
I Added the import and it works, no error.
Thanks !

**Comment by JeroenVinke** [comment]
Great!
