### ISSUE TITLE
kendo.multiselect.min not loaded

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia-ui-toolkits/aurelia-kendoui-bridge#771]
I just updated to kendoui-bridge 1.6.5 and kendoui 2017.3. Since then the multi-select widget does not work anymore because `kendo.multiselect.min.js` does not get loaded anymore.
My config looks like this:
```
        .plugin('aurelia-kendoui-bridge', kendoBridge => {
            kendoBridge
                .kendoMultiSelect()
                .kendoDatePicker();
        })
```

It used to work before. The date picker still works. The error I get is:

```
aurelia-pal.js:39 Uncaught (in promise) Error: Error invoking Multiselect. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: The kendo control 'kendoMultiSelect' is not available. Did you load Kendo (in addition to the bridge)?
Inner Error Stack:
Error: The kendo control 'kendoMultiSelect' is not available. Did you load Kendo (in addition to the bridge)?
    at WidgetBase.control (http://localhost:8835/jspm_packages/npm/aurelia-kendoui-bridge@1.6.5/common/widget-base.js:58:15)
    at new Multiselect (http://localhost:8835/jspm_packages/npm/aurelia-kendoui-bridge@1.6.5/multiselect/multiselect.js:72:36)
    at Object.invoke (http://localhost:8835/jspm_packages/npm/aurelia-dependency-injection@1.3.2/aurelia-dependency-injection.js:461:14)
    at InvocationHandler.invoke (http://localhost:8835/jspm_packages/npm/aurelia-dependency-injection@1.3.2/aurelia-dependency-injection.js:413:168)
    at Container.invoke (http://localhost:8835/jspm_packages/npm/aurelia-dependency-injection@1.3.2/aurelia-dependency-injection.js:684:25)
    at ProviderResolver.get (http://localhost:8835/jspm_packages/npm/aurelia-templating@1.6.0/aurelia-templating.js:2047:74)
    at Container.get (http://localhost:8835/jspm_packages/npm/aurelia-dependency-injection@1.3.2/aurelia-dependency-injection.js:623:23)
    at Container.elementContainerGet [as get] (http://localhost:8835/jspm_packages/npm/aurelia-templating@1.6.0/aurelia-templating.js:2102:17)
    at HtmlBehaviorResource.create (http://localhost:8835/jspm_packages/npm/aurelia-templating@1.6.0/aurelia-templating.js:4090:58)
    at applyInstructions (http://localhost:8835/jspm_packages/npm/aurelia-templating@1.6.0/aurelia-templating.js:2204:33)
```

My quick work-around is a simple `import 'kendo.multiselect.min';`. That works, but it's not how it's supposed to be, is it?

**Comment by adriatic** [comment]
Your quick work-around is indeed the correct method to achieve the expected outcome - your application loading the KendoUI SDK element you want to use (`kendo.multiselect.min`). 

The section in your config:

```
       .plugin('aurelia-kendoui-bridge', kendoBridge => {
            kendoBridge
                .kendoMultiSelect()
                .kendoDatePicker();
        })
```

tells the bridge which bridge components to load (as different from loading them all) and the line `import 'kendo.multiselect.min';` in your application's code ensures that the matching KendoUI widget that will be "wrapped" by the bridge gets loaded as well.

This is generally explained **[here](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html#591-who-loads-kendo)** and (with more details) **[here](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/developers-tutorials/42_skeleton_esnext.html#step-3)**

Since I am always curious about people's approach to documentation, which starts with "I need no documentation" and ends "I will read everything before trying anything", can you tell me where do you belong in this spectrum?

**Comment by Tim-Erwin** [comment]
Ok, I'm sorry then to have bothered you with my request. The funny thing is that I only have to include that line since my recent upgrade. And also I don't have to import the date picker component and it still works, maybe that's a coincedence?

When I read the documentation last year (which I needed) I found everything necessary to get it working. Don't know if the imports are a new thing or if I missed them last year and for some reason it still worked. To be honest I didn't re-read the docs for this issue.

**Comment by adriatic** [comment]
Please do not be sorry for asking questions - we do pride ourselves to support our bridge and we appreciate our customers.

Sometime last year we did significantly improve the bridge by allowing the user to specify the set of KendoUI widgets to be used by the app. Before that, the Bridge would either load all components of the KendoUI Core, or KendoUI Pro. This explains your experience today.

**Comment by Tim-Erwin** [comment]
Thanks a lot for the blazingly fast reply and for maintaining this helpful library.
